### ISSUE TITLE
extend type define of NodeJS.Process.env

### ISSUE THREAD

**Issue by GongT** [types/env-node#39]
installed: `registry:dt/node#6.0.0+20160907103612`

current content:
```ts
 export interface Process extends EventEmitter {
/// ....
    env: any;
/// ....
}
```

may change to:
```ts
export interface EnvironmentVariables {
    [key: string]: string;
}
export interface Process extends EventEmitter {
/// ....
    env: NodeJS.EnvironmentVariables;
/// ....
}
```

then users can extend `env` in their own .d.ts:
```ts
declare namespace NodeJS {
	export interface EnvironmentVariables {
		SOME_THING: string;
		SOME_OTHER_THING: string;
	}
}
```

currently this will cause `error TS2403: Subsequent variable declarations must have the same type.  Variable 'env' must be of type 'any', but here has type 'IProcessEnv'`:
```ts
interface IProcessEnv {
	SOME_THING: string;
	SOME_OTHER_THING: string;
}
declare namespace NodeJS {
	export interface Process {
		env: IProcessEnv;
	}
}
```

**Comment by blakeembrey** [comment]
The `dt` definition comes from https://github.com/DefinitelyTyped/DefinitelyTyped. This should be possible if you install this definition (which is `env~node`).

**Comment by blakeembrey** [comment]
Even then, I never got the code you posted to work. I tried different approaches, but nothing worked on the current TypeScript release unless you're using 2.0 or something.

**Comment by GongT** [comment]
I'm using typescript>2.0 ... LOL
```
tsc --version
Version 2.1.0-dev.20160905
```

**Comment by voxlet** [comment]
@blakeembrey 
> Edit: Someone let me know if they have better luck and then we can change it from an inline type to an interface called Env.

Confirmed this approach works with the current 2.0.6 TypeScript release.
This would be especially useful when using the TSLint `no-string-literal` rule, which currently needs liberal sprinkling of `tslint:disable` comment flags when accessing anything other than `PATH`.

**Comment by blakeembrey** [comment]
I always disable that rule unfortunately, TypeScript development just kind of requires it because you can't access index signatures without it. It'd be nice if TypeScript allowed `process.env.hello` with an index signature, but it doesn't.

**Comment by voxlet** [comment]
Yes, I guess that's true if you need to interface with a lot of external libraries. For my own code, though, I always define separate properties and use index signatures only for dynamic access.

Anyways, I went ahead and made a PR with the changes, if this is still up for consideration!

**Comment by xeoneux** [comment]
@blakeembrey why do I not see these changes when I install @types/node?

**Comment by blakeembrey** [comment]
This repo has nothing to do with NPM. Those come from DefinitelyTyped.

**Comment by xeoneux** [comment]
@blakeembrey how do I install these types then?

**Comment by blakeembrey** [comment]
This whole organisation is used for Typings, if you aren't using Typings, you can't. We've been waiting a year for https://github.com/Microsoft/types-publisher/issues/4 to make it possible.

**Comment by xeoneux** [comment]
@blakeembrey is typings still in development or @types is the official solution?

**Comment by blakeembrey** [comment]
Typings is stable and any issues will continue to be fixed, but it's in a deprecated state and I'd recommend using @types.
